server:
  port: ${PORT:5000}

spring:
  security:
    oauth2:
      client:
        registration:
          commerz:
            authorization-grant-type: authorization_code
            client-id: ${COMMERZ_CLIENT_ID:aab6de52-86ad-4734-8761-779d1fa5deb4}
            client-secret: ${COMMERZ_CLIENT_SECRET:f39bc34f-4887-41cd-8872-ff3332190b43}
            redirect-uri: "{baseUrl}/login/oauth2/callback/commerz"
        provider:
          commerz:
            authorization-uri: https://api-sandbox.commerzbank.com/auth/realms/sandbox/protocol/openid-connect/auth
            token-uri: https://api-sandbox.commerzbank.com/auth/realms/sandbox/protocol/openid-connect/token

commerz:
  api:
    base-url: https://api-sandbox.commerzbank.com/securities-api/v3
    path:
      security-accounts: /security-accounts
      assets: /assets